version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.7
      environment:
        PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: 
          command: |
            sudo pip install pipenv
            pipenv install
            pip install -r requirements.txtgit push orii