version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.7
      environment:
        PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: 
          name: "install requirements"
          command: |
            sudo pip install pipenv
            pipenv install
            pip install -r requirements.txt
      - run:
          name: "run tests"
          command: |
            python test.py